### PR TITLE
Merge cluster API commands into cluster-operator binary

### PR DESCRIPTION
**Pull request by csrwng**
Adds the Cluster API apiserver and controller manager commands to the cluster-operator binary. After this, our Cluster API code will come from what is vendored in to our repo and not from latest master upstream. 

This includes an update of upstream code and changes required to work without a MachineRole in the cluster API machine spec.

### CODE REVIEW

**Comment by csrwng** [comment]
@dgoodwin @joelddiaz - this should be ready for review. I am now running a separate container for the cluster-api apiserver. This has solved the issue with the double registration of the cluster api group.

**Comment by dgoodwin** [comment]
LGTM just a simple integration test failure for an unused import.

**Comment by csrwng** [comment]
Finally, took me a while to get integration tests running again, but it's now fixed

**Pull request merged**
