### PR TITLE
Leverage shorter ELB suffixes in Openshift Ansible

### PR DESCRIPTION
**Pull request by csrwng**

### CODE REVIEW

**Comment by mazzystr** [comment]
What does cp pertain to?

**Comment by staebler** [comment]
The elb names need to be changed in this test, too. https://github.com/openshift/cluster-operator/blob/eed4455eab3791da3bc596d0c42af6d9180c9941/pkg/ansible/generate_test.go#L74

**Comment by staebler** [comment]
> What does cp pertain to?

@mazzystr "cp" refers to control plane.

**Comment by csrwng** [comment]
thx @staebler fixed now

**Pull request merged**
