### PR TITLE
Add a tagSpecification for the instance volume.

### PR DESCRIPTION
**Pull request by abutcher**

### CODE REVIEW

**Comment by csrwng** [comment]
Looks like an issue with CI
/lgtm

**Comment by csrwng** [comment]
@stevekuznetsov is this FORWARD PARAMETERS TO THE REMOTE HOST a known issue?

**Comment by stevekuznetsov** [comment]
Yeah should be fixed

/retest

**Comment by abutcher** [comment]
gofmt wasn't happy :fallen_leaf:

**Pull request merged**
