### PR TITLE
Fix image problems

### PR DESCRIPTION
**Pull request by twiest**
Fix image problems
    - [x] Fix golint installation in docker image build
    - [x] Test that "make images" now works
    - [x] Change cluster-operator images to point to quay.io
    - [x] Test that cluster deploy now works again

### CODE REVIEW

**Comment by dgoodwin** [comment]
We should probably shut down E2E testing on cluster-operator, don't know what this is but it's not worth fixing.

I'd force merge this but I don't have perms. :)

**Comment by twiest** [comment]
@csrwng Hey, would you mind taking a look at this please?

Note that I set the image URLs to `quay.io/twiest/cluster-operator:latest` like we discussed. I don't feel great about that, but it's probably the best thing to do for now.

**Comment by csrwng** [comment]
@twiest my only comment is that it may not be a bad idea to update the registry prefix in the Makefile -> https://github.com/openshift/cluster-operator/blob/master/Makefile#L68 (It's never going to be quay.io/openshift)

**Comment by twiest** [comment]
@csrwng I don't see that variable actually used anywhere. Should I just remove it?

**Comment by csrwng** [comment]
@twiest ha,  you're right. Yup, go ahead and remove i

**Comment by csrwng** [comment]
@twiest we should remove the jenkins/e2e test from the list of tests ... that relied on the images coming from the api.ci registry which no longer exist. I'll submit a PR for that.

/lgtm

**Pull request merged**
