### PR TITLE
Use pre-built images instead of BuildConfig

### PR DESCRIPTION
**Pull request by jhernand**
Currently the deployment playbook uses a `BuildConfig` to build the operator from source during deployment. This is no longer needed, because there are already pre-built images published, so this patch changes the playbook to use those pre-built images.

### CODE REVIEW

**Comment by jhernand** [comment]
@dgoodwin @csrwng @nimrodshn @zgalor after these changes I was able to deploy the operator running `ansible-playbook contrib/ansible/deploy-playbook.yml` and then adding manually the pre-built images to the `cluster-operator` image stream, with the `latest` tag:

```
$ oc project openshift-cluster-operator
$ oc tag registry.svc.ci.openshift.org/openshift-cluster-operator/cluster-operator:latest
```

**Comment by csrwng** [comment]
/lgtm
The build part should not be part of the regular deployment. We will have a separate config for builds in CI.

**Comment by jhernand** [comment]
Thanks @csrwng.

**Comment by dgoodwin** [comment]
Thanks @jhernand !

**Pull request merged**
